install.packages("e1071")
install.packages("randomForest")
install.packages("ggplot2")
install.packages("data.table")
install.packages("Rcpp")
install.packages("digest")
install.packages("psych")
install.packages("dplyr")

library(e1071)
library(randomForest)
library(ggplot2)
library(data.table)
library(Rcpp)
library(digest)
library(psych)
library(dplyr)
